### ISSUE TITLE
Cairo can't build with Tiger's X11

### ISSUE THREAD

**Issue by mistydemeo** [mistydemeo/tigerbrew#69]
Tiger's X11 is far, far too old to build cairo. Cairo mostly is able to tell that this is the case, but still tries to build xlib-xrender and the build consequently fails. Build logs:

https://gist.github.com/anonymous/5695285

X has been disabled as of 4e19c7f94873ae955a5682c6d2d8e41a2645f503. Users who need X on Cairo, let me know and we can see if we can fix it up.

**Comment by ranma42** [comment]
IIRC this is just a problem with the Xlib headers being too old (the cairo-xlib backend should detect what features are provided by the X server and use them or fallback to pixman as appropriate).
Ping me if there is interest in getting this fixed or worked around.

**Comment by ranma42** [comment]
It looks like the issue that caused that build failure has already been fixed in cairo.
The formula could be updated to work (and make proper use of Xlib/XRender when available) easily, while for XCB some more effort would be required. For me, the tricky thing (that I still have to figure out how to fix properly) is the detection of XQuartz/the X environment.
The hacky changes to the formula that I did to test this are available [here](https://gist.github.com/ranma42/35d7521767d5ce8c9c1bc307de5520c2), but a good solution will require someone who actually knows how to write complex brew formulas 😄
