### ISSUE TITLE
Unable to get a working environment from a fresh install under OS X 10.4

### ISSUE THREAD

**Issue by nathanpc** [mistydemeo/tigerbrew#916]
I've done a fresh install on a clean Mac OS X 10.4 G4 installation and unfortunately, due to encryption issues, I was unable to get a working Tigerbrew environment. After the installation running `brew doctor` gives me the following output:

```
==> Please wait... tigers are now brewing
Downloading Tigerbrew's ruby; this may take some time

==> Downloading https://archive.org/download/tigerbrew/portable-ruby-2.3.3.tiger_g3.bottle.tar.gz
curl: (35) error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version
Error: Download failed: https://archive.org/download/tigerbrew/portable-ruby-2.3.3.tiger_g3.bottle.tar.gz
Error: Failed to install vendor Ruby.
```

In order to get it to install I already had to switch the download URLs in the install script to use HTTP. Is there a way to change the URL to use HTTP after it has been installed? Also, it would be important to change this in the repo as well in order to allow new users to perform brand new installations.

**Comment by mistydemeo** [comment]
Well, that's inconvenient. I was using HTTPS for archive.org URLs because, up until now, they were still serving things up using TLS protocol versions that Tiger's libraries supported. I guess that's not true anymore. Sorry about this! I'll look at adjusting both the install script and the bootstrap Ruby/curl to make sure they can be fetched safely.

**Comment by Iemand005** [comment]
I am having the same issue, I can't install tigerbrew nor an older version of the original brew due to curl not supporting the new protocol. I also tried archive.org urls from 2011/2013, but was surprised to see it did not work and gave the same error. Tried proxy server, tried everything. I guess the solution is either stop using curl or download all the files in a package and install from there. Maybe it's possible to update curl on these older macs. I tried MacPorts and it works but there are always issues compiling with old xcode. Super frustrating stuff, hours of trying and failing, staying up late just to give up in the end and be here empty handed. I hope you can get a workaround for the curl issue that suddenly appeared.

**Comment by sevan** [comment]
Take this advices with caution as I'm not familiar with Tigerbrew's internals, but until an appropriate solution is found, can you edit `Library/Homebrew/cmd/vendor-install.sh` & switch the URLS from https to http just so you can get up to date. then switch the URLs back to https to continue with your setup?
Reverting from https to http is bad but you have the hashes there for the files which will be fetched so there's some basic protection.
Once you're there, install the up to date Curl & OpenSSL, undo the changes to `Library/Homebrew/cmd/vendor-install.sh` and continue with your setup via HTTPS.

**Comment by mistydemeo** [comment]
I've just pushed a fix to switch to `http` for these. Since we already check the sha256 hash, it should ensure you're still getting the right binaries. If you can't `brew update` due to the issue, sevan's fix should make it possible for you to get things working.
